# Generated by Django 4.0.2 on 2023-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackfood', '0003_event_alter_donation_wedding_delete_wedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contactDetail',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='contactPerson',
            field=models.CharField(max_length=200),
        ),
    ]
